input:
  data_format:
  data_cols:
  build_mesh: 
  run_spherical_vf:

output:
  output_type:
  output_folder:

mesh:
  save_mesh:
  dtype:
  nbins: 
  is_box:
  box_length:
  box_centre:
  padding:
  do_recon: 
  recon_alg:
  los:
  r_smooth:
  omega_m:
  f:
  bias:

spherical_voids:
  verbose:
  output_fn:
  radii: 
  min_dens_cut:
  max_overlap_frac:

