input:
  data_format:
  data_cols:
  build_mesh: 
  box_length:        # calculated from data if build_mesh=true
  box_centre:        # calculated from data if build_mesh=true
  do_recon:
  run_spherical_vf:

output:
  output_fn:
  output_type:

cosmo:
  h:
  omega_m:
  omega_l:
  f:
  bias:

mesh:
  save_mesh:
  mesh_fn:
  dtype:
  nbins_vf: 
  padding:
  recon_alg:
  nbins_recon:
  los:
  r_smooth:

spherical_voids:
  radii: 
  min_dens_cut:
  max_overlap_frac:

